# Generated by Django 4.2.1 on 2024-07-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_alter_women_is_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedModel',
        ),
    ]
