# Generated by Django 4.2.1 on 2024-09-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_uploadedfile_alter_women_options_alter_women_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
